.PHONY: all day_01 day_02

all: day_01 day_02

day_01:
	@echo "\nDay 1: Trebuchet?!"
	@cargo run -q --manifest-path=day_01/Cargo.toml

day_02:
	@echo "\nDay 2: Cube Conundrum"
	@(cd ./day_02/ && zig build run)
