.PHONY: all day_01

all: day_01

day_01:
	@echo "\nDay 01: Historian Hysteria"
	@cargo run -q --manifest-path=day_01/Cargo.toml

.PHONY: day_02
day_02:
	@echo "Day 02: Red-Nosed Reports"
	@cargo run -q --manifest-path=day_02/Cargo.toml
